apiVersion: v1
kind: Pod
metadata:
  name: test-service
  labels:
    components: test-service
spec:
  containers:
    - name: test-service
      image: jackspades17/test-service
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
